- targets:
  - wpia-gpu-01.dide.ic.ac.uk
  - wpia-gpu-02.dide.ic.ac.uk
  - wpia-gpu-03.dide.ic.ac.uk
  - wpia-gpu-04.dide.ic.ac.uk
  - wpia-gpu-05.dide.ic.ac.uk
  - wpia-gpu-06.dide.ic.ac.uk
  - wpia-gpu-07.dide.ic.ac.uk
